//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anchorData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="anchorData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="anchorPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="anchorRepository" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stripCount" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "anchorData", propOrder = {
    "anchorPath",
    "anchorRepository",
    "stripCount"
})
public class AnchorData {

    protected String anchorPath;
    protected String anchorRepository;
    protected Integer stripCount;

    /**
     * Gets the value of the anchorPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnchorPath() {
        return anchorPath;
    }

    /**
     * Sets the value of the anchorPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnchorPath(String value) {
        this.anchorPath = value;
    }

    /**
     * Gets the value of the anchorRepository property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAnchorRepository() {
        return anchorRepository;
    }

    /**
     * Sets the value of the anchorRepository property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAnchorRepository(String value) {
        this.anchorRepository = value;
    }

    /**
     * Gets the value of the stripCount property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStripCount() {
        return stripCount;
    }

    /**
     * Sets the value of the stripCount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStripCount(Integer value) {
        this.stripCount = value;
    }

}
