//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for fisheyeReviewItemData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fisheyeReviewItemData">
 *   &lt;complexContent>
 *     &lt;extension base="{}reviewItemData">
 *       &lt;sequence>
 *         &lt;element name="anchorData" type="{}anchorData" minOccurs="0"/>
 *         &lt;element name="authorName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="commitDate" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="commitType" type="{}commitType" minOccurs="0"/>
 *         &lt;element name="expandedRevisions" type="{}reviewItemRevisionData" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="fileType" type="{}fileType" minOccurs="0"/>
 *         &lt;element name="fromContentUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fromRevision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="patchUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="repositoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="showAsDiff" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="toContentUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toPath" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toRevision" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fisheyeReviewItemData", propOrder = {
    "anchorData",
    "authorName",
    "commitDate",
    "commitType",
    "expandedRevisions",
    "fileType",
    "fromContentUrl",
    "fromPath",
    "fromRevision",
    "patchUrl",
    "repositoryName",
    "showAsDiff",
    "toContentUrl",
    "toPath",
    "toRevision"
})
public class FisheyeReviewItemData
    extends ReviewItemData
{

    protected AnchorData anchorData;
    protected String authorName;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar commitDate;
    protected CommitType commitType;
    @XmlElement(nillable = true)
    protected List<ReviewItemRevisionData> expandedRevisions;
    protected FileType fileType;
    protected String fromContentUrl;
    protected String fromPath;
    protected String fromRevision;
    protected String patchUrl;
    protected String repositoryName;
    protected Boolean showAsDiff;
    protected String toContentUrl;
    protected String toPath;
    protected String toRevision;

    /**
     * Gets the value of the anchorData property.
     * 
     * @return
     *     possible object is
     *     {@link AnchorData }
     *     
     */
    public AnchorData getAnchorData() {
        return anchorData;
    }

    /**
     * Sets the value of the anchorData property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnchorData }
     *     
     */
    public void setAnchorData(AnchorData value) {
        this.anchorData = value;
    }

    /**
     * Gets the value of the authorName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * Sets the value of the authorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuthorName(String value) {
        this.authorName = value;
    }

    /**
     * Gets the value of the commitDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCommitDate() {
        return commitDate;
    }

    /**
     * Sets the value of the commitDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCommitDate(XMLGregorianCalendar value) {
        this.commitDate = value;
    }

    /**
     * Gets the value of the commitType property.
     * 
     * @return
     *     possible object is
     *     {@link CommitType }
     *     
     */
    public CommitType getCommitType() {
        return commitType;
    }

    /**
     * Sets the value of the commitType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CommitType }
     *     
     */
    public void setCommitType(CommitType value) {
        this.commitType = value;
    }

    /**
     * Gets the value of the expandedRevisions property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the expandedRevisions property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExpandedRevisions().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReviewItemRevisionData }
     * 
     * 
     */
    public List<ReviewItemRevisionData> getExpandedRevisions() {
        if (expandedRevisions == null) {
            expandedRevisions = new ArrayList<ReviewItemRevisionData>();
        }
        return this.expandedRevisions;
    }

    /**
     * Gets the value of the fileType property.
     * 
     * @return
     *     possible object is
     *     {@link FileType }
     *     
     */
    public FileType getFileType() {
        return fileType;
    }

    /**
     * Sets the value of the fileType property.
     * 
     * @param value
     *     allowed object is
     *     {@link FileType }
     *     
     */
    public void setFileType(FileType value) {
        this.fileType = value;
    }

    /**
     * Gets the value of the fromContentUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromContentUrl() {
        return fromContentUrl;
    }

    /**
     * Sets the value of the fromContentUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromContentUrl(String value) {
        this.fromContentUrl = value;
    }

    /**
     * Gets the value of the fromPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromPath() {
        return fromPath;
    }

    /**
     * Sets the value of the fromPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromPath(String value) {
        this.fromPath = value;
    }

    /**
     * Gets the value of the fromRevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromRevision() {
        return fromRevision;
    }

    /**
     * Sets the value of the fromRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromRevision(String value) {
        this.fromRevision = value;
    }

    /**
     * Gets the value of the patchUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPatchUrl() {
        return patchUrl;
    }

    /**
     * Sets the value of the patchUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPatchUrl(String value) {
        this.patchUrl = value;
    }

    /**
     * Gets the value of the repositoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRepositoryName() {
        return repositoryName;
    }

    /**
     * Sets the value of the repositoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRepositoryName(String value) {
        this.repositoryName = value;
    }

    /**
     * Gets the value of the showAsDiff property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isShowAsDiff() {
        return showAsDiff;
    }

    /**
     * Sets the value of the showAsDiff property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowAsDiff(Boolean value) {
        this.showAsDiff = value;
    }

    /**
     * Gets the value of the toContentUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToContentUrl() {
        return toContentUrl;
    }

    /**
     * Sets the value of the toContentUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToContentUrl(String value) {
        this.toContentUrl = value;
    }

    /**
     * Gets the value of the toPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToPath() {
        return toPath;
    }

    /**
     * Sets the value of the toPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToPath(String value) {
        this.toPath = value;
    }

    /**
     * Gets the value of the toRevision property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToRevision() {
        return toRevision;
    }

    /**
     * Sets the value of the toRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToRevision(String value) {
        this.toRevision = value;
    }

}
