//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fisheyeReviewItemAttibutes complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fisheyeReviewItemAttibutes">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="added" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="copied" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="deleted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="modified" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="moved" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fisheyeReviewItemAttibutes", propOrder = {
    "added",
    "copied",
    "deleted",
    "modified",
    "moved"
})
public class FisheyeReviewItemAttibutes {

    protected boolean added;
    protected boolean copied;
    protected boolean deleted;
    protected boolean modified;
    protected boolean moved;

    /**
     * Gets the value of the added property.
     * 
     */
    public boolean isAdded() {
        return added;
    }

    /**
     * Sets the value of the added property.
     * 
     */
    public void setAdded(boolean value) {
        this.added = value;
    }

    /**
     * Gets the value of the copied property.
     * 
     */
    public boolean isCopied() {
        return copied;
    }

    /**
     * Sets the value of the copied property.
     * 
     */
    public void setCopied(boolean value) {
        this.copied = value;
    }

    /**
     * Gets the value of the deleted property.
     * 
     */
    public boolean isDeleted() {
        return deleted;
    }

    /**
     * Sets the value of the deleted property.
     * 
     */
    public void setDeleted(boolean value) {
        this.deleted = value;
    }

    /**
     * Gets the value of the modified property.
     * 
     */
    public boolean isModified() {
        return modified;
    }

    /**
     * Sets the value of the modified property.
     * 
     */
    public void setModified(boolean value) {
        this.modified = value;
    }

    /**
     * Gets the value of the moved property.
     * 
     */
    public boolean isMoved() {
        return moved;
    }

    /**
     * Sets the value of the moved property.
     * 
     */
    public void setMoved(boolean value) {
        this.moved = value;
    }

}
