//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.eui.fedex.crucible.generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PluginRepositoryData_QNAME = new QName("", "pluginRepositoryData");
    private final static QName _HgRepositoryData_QNAME = new QName("", "hgRepositoryData");
    private final static QName _ReviewItems_QNAME = new QName("", "reviewItems");
    private final static QName _DetailedReviewData_QNAME = new QName("", "detailedReviewData");
    private final static QName _CrucibleRevisionData_QNAME = new QName("", "crucibleRevisionData");
    private final static QName _UserData_QNAME = new QName("", "userData");
    private final static QName _Anchor_QNAME = new QName("", "anchor");
    private final static QName _GitRepositoryData_QNAME = new QName("", "gitRepositoryData");
    private final static QName _ChangesetData_QNAME = new QName("", "changesetData");
    private final static QName _P4RepositoryData_QNAME = new QName("", "p4RepositoryData");
    private final static QName _LoginResult_QNAME = new QName("", "loginResult");
    private final static QName _VersionInfo_QNAME = new QName("", "versionInfo");
    private final static QName _GeneralCommentData_QNAME = new QName("", "generalCommentData");
    private final static QName _CommentStats_QNAME = new QName("", "commentStats");
    private final static QName _ReviewItem_QNAME = new QName("", "reviewItem");
    private final static QName _CustomFilterData_QNAME = new QName("", "customFilterData");
    private final static QName _Reviewers_QNAME = new QName("", "reviewers");
    private final static QName _ReviewData_QNAME = new QName("", "reviewData");
    private final static QName _CvsRepositoryData_QNAME = new QName("", "cvsRepositoryData");
    private final static QName _CustomFieldData_QNAME = new QName("", "customFieldData");
    private final static QName _CommitterData_QNAME = new QName("", "committerData");
    private final static QName _VersionedLineCommentData_QNAME = new QName("", "versionedLineCommentData");
    private final static QName _SvnRepositoryData_QNAME = new QName("", "svnRepositoryData");
    private final static QName _Transitions_QNAME = new QName("", "transitions");
    private final static QName _ReviewItemRevisionData_QNAME = new QName("", "reviewItemRevisionData");
    private final static QName _ReviewerData_QNAME = new QName("", "reviewerData");
    private final static QName _Actions_QNAME = new QName("", "actions");
    private final static QName _Comments_QNAME = new QName("", "comments");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.eui.fedex.crucible.generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ReviewerData }
     * 
     */
    public ReviewerData createReviewerData() {
        return new ReviewerData();
    }

    /**
     * Create an instance of {@link FisheyeReviewItemData }
     * 
     */
    public FisheyeReviewItemData createFisheyeReviewItemData() {
        return new FisheyeReviewItemData();
    }

    /**
     * Create an instance of {@link ParticipantStatus }
     * 
     */
    public ParticipantStatus createParticipantStatus() {
        return new ParticipantStatus();
    }

    /**
     * Create an instance of {@link CustomFilterData }
     * 
     */
    public CustomFilterData createCustomFilterData() {
        return new CustomFilterData();
    }

    /**
     * Create an instance of {@link Reviewers }
     * 
     */
    public Reviewers createReviewers() {
        return new Reviewers();
    }

    /**
     * Create an instance of {@link ChangesetData }
     * 
     */
    public ChangesetData createChangesetData() {
        return new ChangesetData();
    }

    /**
     * Create an instance of {@link SvnRepositoryData }
     * 
     */
    public SvnRepositoryData createSvnRepositoryData() {
        return new SvnRepositoryData();
    }

    /**
     * Create an instance of {@link VersionInfo }
     * 
     */
    public VersionInfo createVersionInfo() {
        return new VersionInfo();
    }

    /**
     * Create an instance of {@link Actions }
     * 
     */
    public Actions createActions() {
        return new Actions();
    }

    /**
     * Create an instance of {@link GeneralCommentData }
     * 
     */
    public GeneralCommentData createGeneralCommentData() {
        return new GeneralCommentData();
    }

    /**
     * Create an instance of {@link AnchorData }
     * 
     */
    public AnchorData createAnchorData() {
        return new AnchorData();
    }

    /**
     * Create an instance of {@link Transitions }
     * 
     */
    public Transitions createTransitions() {
        return new Transitions();
    }

    /**
     * Create an instance of {@link ReviewItemRevisionData }
     * 
     */
    public ReviewItemRevisionData createReviewItemRevisionData() {
        return new ReviewItemRevisionData();
    }

    /**
     * Create an instance of {@link CustomFieldDefData }
     * 
     */
    public CustomFieldDefData createCustomFieldDefData() {
        return new CustomFieldDefData();
    }

    /**
     * Create an instance of {@link VersionedLineCommentBuilder }
     * 
     */
    public VersionedLineCommentBuilder createVersionedLineCommentBuilder() {
        return new VersionedLineCommentBuilder();
    }

    /**
     * Create an instance of {@link VersionedLineCommentData.LineRanges }
     * 
     */
    public VersionedLineCommentData.LineRanges createVersionedLineCommentDataLineRanges() {
        return new VersionedLineCommentData.LineRanges();
    }

    /**
     * Create an instance of {@link CommentStats }
     * 
     */
    public CommentStats createCommentStats() {
        return new CommentStats();
    }

    /**
     * Create an instance of {@link CrucibleRevisionData }
     * 
     */
    public CrucibleRevisionData createCrucibleRevisionData() {
        return new CrucibleRevisionData();
    }

    /**
     * Create an instance of {@link CommentDataImpl.Metrics.Entry }
     * 
     */
    public CommentDataImpl.Metrics.Entry createCommentDataImplMetricsEntry() {
        return new CommentDataImpl.Metrics.Entry();
    }

    /**
     * Create an instance of {@link ReviewData }
     * 
     */
    public ReviewData createReviewData() {
        return new ReviewData();
    }

    /**
     * Create an instance of {@link Comments }
     * 
     */
    public Comments createComments() {
        return new Comments();
    }

    /**
     * Create an instance of {@link VersionedLineCommentData }
     * 
     */
    public VersionedLineCommentData createVersionedLineCommentData() {
        return new VersionedLineCommentData();
    }

    /**
     * Create an instance of {@link CommentDataImpl.Metrics }
     * 
     */
    public CommentDataImpl.Metrics createCommentDataImplMetrics() {
        return new CommentDataImpl.Metrics();
    }

    /**
     * Create an instance of {@link GitRepositoryData }
     * 
     */
    public GitRepositoryData createGitRepositoryData() {
        return new GitRepositoryData();
    }

    /**
     * Create an instance of {@link DetailedReviewData }
     * 
     */
    public DetailedReviewData createDetailedReviewData() {
        return new DetailedReviewData();
    }

    /**
     * Create an instance of {@link Iso8601DateAdapter }
     * 
     */
    public Iso8601DateAdapter createIso8601DateAdapter() {
        return new Iso8601DateAdapter();
    }

    /**
     * Create an instance of {@link CustomFieldData }
     * 
     */
    public CustomFieldData createCustomFieldData() {
        return new CustomFieldData();
    }

    /**
     * Create an instance of {@link CustomFieldValue }
     * 
     */
    public CustomFieldValue createCustomFieldValue() {
        return new CustomFieldValue();
    }

    /**
     * Create an instance of {@link DetailedReviewData.Stats }
     * 
     */
    public DetailedReviewData.Stats createDetailedReviewDataStats() {
        return new DetailedReviewData.Stats();
    }

    /**
     * Create an instance of {@link P4RepositoryData }
     * 
     */
    public P4RepositoryData createP4RepositoryData() {
        return new P4RepositoryData();
    }

    /**
     * Create an instance of {@link CommitterData }
     * 
     */
    public CommitterData createCommitterData() {
        return new CommitterData();
    }

    /**
     * Create an instance of {@link FisheyeReviewItemAttibutes }
     * 
     */
    public FisheyeReviewItemAttibutes createFisheyeReviewItemAttibutes() {
        return new FisheyeReviewItemAttibutes();
    }

    /**
     * Create an instance of {@link HgRepositoryData }
     * 
     */
    public HgRepositoryData createHgRepositoryData() {
        return new HgRepositoryData();
    }

    /**
     * Create an instance of {@link LineRangeDetail }
     * 
     */
    public LineRangeDetail createLineRangeDetail() {
        return new LineRangeDetail();
    }

    /**
     * Create an instance of {@link ReviewItemData }
     * 
     */
    public ReviewItemData createReviewItemData() {
        return new ReviewItemData();
    }

    /**
     * Create an instance of {@link ReviewItems }
     * 
     */
    public ReviewItems createReviewItems() {
        return new ReviewItems();
    }

    /**
     * Create an instance of {@link UserData }
     * 
     */
    public UserData createUserData() {
        return new UserData();
    }

    /**
     * Create an instance of {@link CvsRepositoryData }
     * 
     */
    public CvsRepositoryData createCvsRepositoryData() {
        return new CvsRepositoryData();
    }

    /**
     * Create an instance of {@link PluginRepositoryData }
     * 
     */
    public PluginRepositoryData createPluginRepositoryData() {
        return new PluginRepositoryData();
    }

    /**
     * Create an instance of {@link CommentDataImpl }
     * 
     */
    public CommentDataImpl createCommentDataImpl() {
        return new CommentDataImpl();
    }

    /**
     * Create an instance of {@link ProjectDataBuilder }
     * 
     */
    public ProjectDataBuilder createProjectDataBuilder() {
        return new ProjectDataBuilder();
    }

    /**
     * Create an instance of {@link LoginResult }
     * 
     */
    public LoginResult createLoginResult() {
        return new LoginResult();
    }

    /**
     * Create an instance of {@link ActionData }
     * 
     */
    public ActionData createActionData() {
        return new ActionData();
    }

    /**
     * Create an instance of {@link RepositoryData }
     * 
     */
    public RepositoryData createRepositoryData() {
        return new RepositoryData();
    }

    /**
     * Create an instance of {@link UserProfileData }
     * 
     */
    public UserProfileData createUserProfileData() {
        return new UserProfileData();
    }

    /**
     * Create an instance of {@link ReviewItemData.Participants }
     * 
     */
    public ReviewItemData.Participants createReviewItemDataParticipants() {
        return new ReviewItemData.Participants();
    }

    /**
     * Create an instance of {@link CommentDataImpl.Replies }
     * 
     */
    public CommentDataImpl.Replies createCommentDataImplReplies() {
        return new CommentDataImpl.Replies();
    }

    /**
     * Create an instance of {@link ProjectData }
     * 
     */
    public ProjectData createProjectData() {
        return new ProjectData();
    }

    /**
     * Create an instance of {@link PermId }
     * 
     */
    public PermId createPermId() {
        return new PermId();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PluginRepositoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pluginRepositoryData")
    public JAXBElement<PluginRepositoryData> createPluginRepositoryData(PluginRepositoryData value) {
        return new JAXBElement<PluginRepositoryData>(_PluginRepositoryData_QNAME, PluginRepositoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link HgRepositoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "hgRepositoryData")
    public JAXBElement<HgRepositoryData> createHgRepositoryData(HgRepositoryData value) {
        return new JAXBElement<HgRepositoryData>(_HgRepositoryData_QNAME, HgRepositoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReviewItems }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reviewItems")
    public JAXBElement<ReviewItems> createReviewItems(ReviewItems value) {
        return new JAXBElement<ReviewItems>(_ReviewItems_QNAME, ReviewItems.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DetailedReviewData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "detailedReviewData")
    public JAXBElement<DetailedReviewData> createDetailedReviewData(DetailedReviewData value) {
        return new JAXBElement<DetailedReviewData>(_DetailedReviewData_QNAME, DetailedReviewData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CrucibleRevisionData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "crucibleRevisionData")
    public JAXBElement<CrucibleRevisionData> createCrucibleRevisionData(CrucibleRevisionData value) {
        return new JAXBElement<CrucibleRevisionData>(_CrucibleRevisionData_QNAME, CrucibleRevisionData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "userData")
    public JAXBElement<UserData> createUserData(UserData value) {
        return new JAXBElement<UserData>(_UserData_QNAME, UserData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnchorData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "anchor")
    public JAXBElement<AnchorData> createAnchor(AnchorData value) {
        return new JAXBElement<AnchorData>(_Anchor_QNAME, AnchorData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GitRepositoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "gitRepositoryData")
    public JAXBElement<GitRepositoryData> createGitRepositoryData(GitRepositoryData value) {
        return new JAXBElement<GitRepositoryData>(_GitRepositoryData_QNAME, GitRepositoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChangesetData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "changesetData")
    public JAXBElement<ChangesetData> createChangesetData(ChangesetData value) {
        return new JAXBElement<ChangesetData>(_ChangesetData_QNAME, ChangesetData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link P4RepositoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "p4RepositoryData")
    public JAXBElement<P4RepositoryData> createP4RepositoryData(P4RepositoryData value) {
        return new JAXBElement<P4RepositoryData>(_P4RepositoryData_QNAME, P4RepositoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResult }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "loginResult")
    public JAXBElement<LoginResult> createLoginResult(LoginResult value) {
        return new JAXBElement<LoginResult>(_LoginResult_QNAME, LoginResult.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "versionInfo")
    public JAXBElement<VersionInfo> createVersionInfo(VersionInfo value) {
        return new JAXBElement<VersionInfo>(_VersionInfo_QNAME, VersionInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeneralCommentData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "generalCommentData")
    public JAXBElement<GeneralCommentData> createGeneralCommentData(GeneralCommentData value) {
        return new JAXBElement<GeneralCommentData>(_GeneralCommentData_QNAME, GeneralCommentData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommentStats }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "commentStats")
    public JAXBElement<CommentStats> createCommentStats(CommentStats value) {
        return new JAXBElement<CommentStats>(_CommentStats_QNAME, CommentStats.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FisheyeReviewItemData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reviewItem")
    public JAXBElement<FisheyeReviewItemData> createReviewItem(FisheyeReviewItemData value) {
        return new JAXBElement<FisheyeReviewItemData>(_ReviewItem_QNAME, FisheyeReviewItemData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomFilterData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customFilterData")
    public JAXBElement<CustomFilterData> createCustomFilterData(CustomFilterData value) {
        return new JAXBElement<CustomFilterData>(_CustomFilterData_QNAME, CustomFilterData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Reviewers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reviewers")
    public JAXBElement<Reviewers> createReviewers(Reviewers value) {
        return new JAXBElement<Reviewers>(_Reviewers_QNAME, Reviewers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReviewData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reviewData")
    public JAXBElement<ReviewData> createReviewData(ReviewData value) {
        return new JAXBElement<ReviewData>(_ReviewData_QNAME, ReviewData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CvsRepositoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "cvsRepositoryData")
    public JAXBElement<CvsRepositoryData> createCvsRepositoryData(CvsRepositoryData value) {
        return new JAXBElement<CvsRepositoryData>(_CvsRepositoryData_QNAME, CvsRepositoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomFieldData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "customFieldData")
    public JAXBElement<CustomFieldData> createCustomFieldData(CustomFieldData value) {
        return new JAXBElement<CustomFieldData>(_CustomFieldData_QNAME, CustomFieldData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CommitterData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "committerData")
    public JAXBElement<CommitterData> createCommitterData(CommitterData value) {
        return new JAXBElement<CommitterData>(_CommitterData_QNAME, CommitterData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionedLineCommentData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "versionedLineCommentData")
    public JAXBElement<VersionedLineCommentData> createVersionedLineCommentData(VersionedLineCommentData value) {
        return new JAXBElement<VersionedLineCommentData>(_VersionedLineCommentData_QNAME, VersionedLineCommentData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SvnRepositoryData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "svnRepositoryData")
    public JAXBElement<SvnRepositoryData> createSvnRepositoryData(SvnRepositoryData value) {
        return new JAXBElement<SvnRepositoryData>(_SvnRepositoryData_QNAME, SvnRepositoryData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Transitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "transitions")
    public JAXBElement<Transitions> createTransitions(Transitions value) {
        return new JAXBElement<Transitions>(_Transitions_QNAME, Transitions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReviewItemRevisionData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reviewItemRevisionData")
    public JAXBElement<ReviewItemRevisionData> createReviewItemRevisionData(ReviewItemRevisionData value) {
        return new JAXBElement<ReviewItemRevisionData>(_ReviewItemRevisionData_QNAME, ReviewItemRevisionData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReviewerData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "reviewerData")
    public JAXBElement<ReviewerData> createReviewerData(ReviewerData value) {
        return new JAXBElement<ReviewerData>(_ReviewerData_QNAME, ReviewerData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Actions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "actions")
    public JAXBElement<Actions> createActions(Actions value) {
        return new JAXBElement<Actions>(_Actions_QNAME, Actions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Comments }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "comments")
    public JAXBElement<Comments> createComments(Comments value) {
        return new JAXBElement<Comments>(_Comments_QNAME, Comments.class, null, value);
    }

}
