//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for pluginRepositoryData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="pluginRepositoryData">
 *   &lt;complexContent>
 *     &lt;extension base="{}repositoryData">
 *       &lt;sequence>
 *         &lt;element name="available" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="hasChangelogBrowser" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="hasDirectoryBrowser" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="pluginKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stateDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "pluginRepositoryData", propOrder = {
    "available",
    "description",
    "hasChangelogBrowser",
    "hasDirectoryBrowser",
    "pluginKey",
    "stateDescription"
})
public class PluginRepositoryData
    extends RepositoryData
{

    protected boolean available;
    protected String description;
    protected boolean hasChangelogBrowser;
    protected boolean hasDirectoryBrowser;
    protected String pluginKey;
    protected String stateDescription;

    /**
     * Gets the value of the available property.
     * 
     */
    public boolean isAvailable() {
        return available;
    }

    /**
     * Sets the value of the available property.
     * 
     */
    public void setAvailable(boolean value) {
        this.available = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the hasChangelogBrowser property.
     * 
     */
    public boolean isHasChangelogBrowser() {
        return hasChangelogBrowser;
    }

    /**
     * Sets the value of the hasChangelogBrowser property.
     * 
     */
    public void setHasChangelogBrowser(boolean value) {
        this.hasChangelogBrowser = value;
    }

    /**
     * Gets the value of the hasDirectoryBrowser property.
     * 
     */
    public boolean isHasDirectoryBrowser() {
        return hasDirectoryBrowser;
    }

    /**
     * Sets the value of the hasDirectoryBrowser property.
     * 
     */
    public void setHasDirectoryBrowser(boolean value) {
        this.hasDirectoryBrowser = value;
    }

    /**
     * Gets the value of the pluginKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPluginKey() {
        return pluginKey;
    }

    /**
     * Sets the value of the pluginKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPluginKey(String value) {
        this.pluginKey = value;
    }

    /**
     * Gets the value of the stateDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateDescription() {
        return stateDescription;
    }

    /**
     * Sets the value of the stateDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateDescription(String value) {
        this.stateDescription = value;
    }

}
