//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for projectData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="projectData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowReviewersToJoin" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="allowedReviewers" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="defaultDuration" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="defaultModerator" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultObjectives" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultRepositoryName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="defaultReviewerUsers" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="moderatorEnabled" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="permissionSchemeId" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "projectData", propOrder = {
    "allowReviewersToJoin",
    "allowedReviewers",
    "defaultDuration",
    "defaultModerator",
    "defaultObjectives",
    "defaultRepositoryName",
    "defaultReviewerUsers",
    "id",
    "key",
    "moderatorEnabled",
    "name",
    "permissionSchemeId"
})
public class ProjectData {

    protected boolean allowReviewersToJoin;
    @XmlElement(nillable = true)
    protected List<String> allowedReviewers;
    protected Integer defaultDuration;
    protected String defaultModerator;
    protected String defaultObjectives;
    protected String defaultRepositoryName;
    @XmlElement(nillable = true)
    protected List<String> defaultReviewerUsers;
    protected int id;
    protected String key;
    protected boolean moderatorEnabled;
    protected String name;
    protected int permissionSchemeId;

    /**
     * Gets the value of the allowReviewersToJoin property.
     * 
     */
    public boolean isAllowReviewersToJoin() {
        return allowReviewersToJoin;
    }

    /**
     * Sets the value of the allowReviewersToJoin property.
     * 
     */
    public void setAllowReviewersToJoin(boolean value) {
        this.allowReviewersToJoin = value;
    }

    /**
     * Gets the value of the allowedReviewers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedReviewers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedReviewers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAllowedReviewers() {
        if (allowedReviewers == null) {
            allowedReviewers = new ArrayList<String>();
        }
        return this.allowedReviewers;
    }

    /**
     * Gets the value of the defaultDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDefaultDuration() {
        return defaultDuration;
    }

    /**
     * Sets the value of the defaultDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDefaultDuration(Integer value) {
        this.defaultDuration = value;
    }

    /**
     * Gets the value of the defaultModerator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultModerator() {
        return defaultModerator;
    }

    /**
     * Sets the value of the defaultModerator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultModerator(String value) {
        this.defaultModerator = value;
    }

    /**
     * Gets the value of the defaultObjectives property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultObjectives() {
        return defaultObjectives;
    }

    /**
     * Sets the value of the defaultObjectives property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultObjectives(String value) {
        this.defaultObjectives = value;
    }

    /**
     * Gets the value of the defaultRepositoryName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultRepositoryName() {
        return defaultRepositoryName;
    }

    /**
     * Sets the value of the defaultRepositoryName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultRepositoryName(String value) {
        this.defaultRepositoryName = value;
    }

    /**
     * Gets the value of the defaultReviewerUsers property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the defaultReviewerUsers property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDefaultReviewerUsers().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getDefaultReviewerUsers() {
        if (defaultReviewerUsers == null) {
            defaultReviewerUsers = new ArrayList<String>();
        }
        return this.defaultReviewerUsers;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the moderatorEnabled property.
     * 
     */
    public boolean isModeratorEnabled() {
        return moderatorEnabled;
    }

    /**
     * Sets the value of the moderatorEnabled property.
     * 
     */
    public void setModeratorEnabled(boolean value) {
        this.moderatorEnabled = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the permissionSchemeId property.
     * 
     */
    public int getPermissionSchemeId() {
        return permissionSchemeId;
    }

    /**
     * Sets the value of the permissionSchemeId property.
     * 
     */
    public void setPermissionSchemeId(int value) {
        this.permissionSchemeId = value;
    }

}
