//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import java.util.ArrayList ;
import java.util.List ;

import javax.xml.bind.annotation.XmlAccessType ;
import javax.xml.bind.annotation.XmlAccessorType ;
import javax.xml.bind.annotation.XmlSeeAlso ;
import javax.xml.bind.annotation.XmlType ;

import org.codehaus.jackson.annotate.JsonWriteNullProperties ;

/**
 * <p>Java class for reviewData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reviewData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowReviewersToJoin" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="author" type="{}userData" minOccurs="0"/>
 *         &lt;element name="closeDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="createDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creator" type="{}userData" minOccurs="0"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="dueDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="jiraIssueKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="metricsVersion" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="moderator" type="{}userData" minOccurs="0"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="parentReview" type="{}permId" minOccurs="0"/>
 *         &lt;element name="permaId" type="{}permId" minOccurs="0"/>
 *         &lt;element name="permaIdHistory" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="projectKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="reminderDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="state" type="{}state" minOccurs="0"/>
 *         &lt;element name="summary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="type" type="{}reviewType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reviewData", propOrder = {
    "allowReviewersToJoin",
    "author",
    "closeDate",
    "createDate",
    "creator",
    "description",
    "dueDate",
    "jiraIssueKey",
    "metricsVersion",
    "moderator",
    "name",
    "parentReview",
    "permaId",
    "permaIdHistory",
    "projectKey",
    "reminderDate",
    "state",
    "summary",
    "type"
})
@XmlSeeAlso({
    DetailedReviewData.class
})
public class ReviewData {

    protected Boolean allowReviewersToJoin;
    protected UserData author;
    protected String closeDate;
    protected String createDate;
    protected UserData creator;
    protected String description;
    protected String dueDate;
    protected String jiraIssueKey;
    protected int metricsVersion;
    protected UserData moderator;
    protected String name;
    @JsonWriteNullProperties(false)
    protected PermId parentReview;
    @JsonWriteNullProperties(false)
    protected PermId permaId;
//    @XmlElement(nillable = true)
    @JsonWriteNullProperties(false)
    protected List<String> permaIdHistory;
    protected String projectKey;
    protected String reminderDate;
    protected State state;
    protected String summary;
    protected ReviewType type;

    /**
     * Gets the value of the allowReviewersToJoin property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowReviewersToJoin() {
        return allowReviewersToJoin;
    }

    /**
     * Sets the value of the allowReviewersToJoin property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowReviewersToJoin(Boolean value) {
        this.allowReviewersToJoin = value;
    }

    /**
     * Gets the value of the author property.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getAuthor() {
        return author;
    }

    /**
     * Sets the value of the author property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setAuthor(UserData value) {
        this.author = value;
    }

    /**
     * Gets the value of the closeDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloseDate() {
        return closeDate;
    }

    /**
     * Sets the value of the closeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloseDate(String value) {
        this.closeDate = value;
    }

    /**
     * Gets the value of the createDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCreateDate() {
        return createDate;
    }

    /**
     * Sets the value of the createDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCreateDate(String value) {
        this.createDate = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setCreator(UserData value) {
        this.creator = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDueDate(String value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the jiraIssueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJiraIssueKey() {
        return jiraIssueKey;
    }

    /**
     * Sets the value of the jiraIssueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJiraIssueKey(String value) {
        this.jiraIssueKey = value;
    }

    /**
     * Gets the value of the metricsVersion property.
     * 
     */
    public int getMetricsVersion() {
        return metricsVersion;
    }

    /**
     * Sets the value of the metricsVersion property.
     * 
     */
    public void setMetricsVersion(int value) {
        this.metricsVersion = value;
    }

    /**
     * Gets the value of the moderator property.
     * 
     * @return
     *     possible object is
     *     {@link UserData }
     *     
     */
    public UserData getModerator() {
        return moderator;
    }

    /**
     * Sets the value of the moderator property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserData }
     *     
     */
    public void setModerator(UserData value) {
        this.moderator = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the parentReview property.
     * 
     * @return
     *     possible object is
     *     {@link PermId }
     *     
     */
    public PermId getParentReview() {
        return parentReview;
    }

    /**
     * Sets the value of the parentReview property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermId }
     *     
     */
    public void setParentReview(PermId value) {
        this.parentReview = value;
    }

    /**
     * Gets the value of the permaId property.
     * 
     * @return
     *     possible object is
     *     {@link PermId }
     *     
     */
    public PermId getPermaId() {
        return permaId;
    }

    /**
     * Sets the value of the permaId property.
     * 
     * @param value
     *     allowed object is
     *     {@link PermId }
     *     
     */
    public void setPermaId(PermId value) {
        this.permaId = value;
    }

    
    public void setPermaIdHistory( List<String> permaIdHistory ) {
			this.permaIdHistory = permaIdHistory ;
		}

		/**
     * Gets the value of the permaIdHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the permaIdHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPermaIdHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getPermaIdHistory() {
        if (permaIdHistory == null) {
            permaIdHistory = new ArrayList<String>();
        }
        return this.permaIdHistory;
    }

    /**
     * Gets the value of the projectKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectKey() {
        return projectKey;
    }

    /**
     * Sets the value of the projectKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectKey(String value) {
        this.projectKey = value;
    }

    /**
     * Gets the value of the reminderDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReminderDate() {
        return reminderDate;
    }

    /**
     * Sets the value of the reminderDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReminderDate(String value) {
        this.reminderDate = value;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link State }
     *     
     */
    public State getState() {
        return state;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link State }
     *     
     */
    public void setState(State value) {
        this.state = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummary(String value) {
        this.summary = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link ReviewType }
     *     
     */
    public ReviewType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReviewType }
     *     
     */
    public void setType(ReviewType value) {
        this.type = value;
    }

	@Override
	public String toString() {
		return "ReviewData [allowReviewersToJoin=" + allowReviewersToJoin
				+ ", author=" + author + ", closeDate=" + closeDate
				+ ", createDate=" + createDate + ", creator=" + creator
				+ ", description=" + description + ", dueDate=" + dueDate
				+ ", jiraIssueKey=" + jiraIssueKey + ", metricsVersion="
				+ metricsVersion + ", moderator=" + moderator + ", name="
				+ name + ", parentReview=" + parentReview + ", permaId="
				+ permaId //+ //", permaIdHistory=" + permaIdHistory
				+ ", projectKey=" + projectKey + ", reminderDate="
				+ reminderDate + ", state=" + state + ", summary=" + summary
				+ ", type=" + type + "]";
	}
    
    

}
