//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.03.15 at 10:57:54 PM MDT 
//


package com.loquatic.crucible.rest.api;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for versionedLineCommentData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="versionedLineCommentData">
 *   &lt;complexContent>
 *     &lt;extension base="{}versionedCommentData">
 *       &lt;sequence>
 *         &lt;element name="fromLineRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toLineRange" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="lineRanges" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="lineRange" type="{}lineRangeDetail" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "versionedLineCommentData", propOrder = {
    "fromLineRange",
    "toLineRange",
    "lineRanges"
})
public class VersionedLineCommentData
    extends VersionedCommentData
{

    protected String fromLineRange;
    protected String toLineRange;
    protected VersionedLineCommentData.LineRanges lineRanges;

    /**
     * Gets the value of the fromLineRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFromLineRange() {
        return fromLineRange;
    }

    /**
     * Sets the value of the fromLineRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFromLineRange(String value) {
        this.fromLineRange = value;
    }

    /**
     * Gets the value of the toLineRange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToLineRange() {
        return toLineRange;
    }

    /**
     * Sets the value of the toLineRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToLineRange(String value) {
        this.toLineRange = value;
    }

    /**
     * Gets the value of the lineRanges property.
     * 
     * @return
     *     possible object is
     *     {@link VersionedLineCommentData.LineRanges }
     *     
     */
    public VersionedLineCommentData.LineRanges getLineRanges() {
        return lineRanges;
    }

    /**
     * Sets the value of the lineRanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link VersionedLineCommentData.LineRanges }
     *     
     */
    public void setLineRanges(VersionedLineCommentData.LineRanges value) {
        this.lineRanges = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="lineRange" type="{}lineRangeDetail" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lineRange"
    })
    public static class LineRanges {

        protected List<LineRangeDetail> lineRange;

        /**
         * Gets the value of the lineRange property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the lineRange property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getLineRange().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link LineRangeDetail }
         * 
         * 
         */
        public List<LineRangeDetail> getLineRange() {
            if (lineRange == null) {
                lineRange = new ArrayList<LineRangeDetail>();
            }
            return this.lineRange;
        }

    }

}
